apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: henry-mhene-cluster
  region: ap-southeast-2
  version: "1.17"

managedNodeGroups:
  - name: ng-1
    labels: { role: websites }
    tags:
      nodegroup-role: website
    instanceType: t2.nano
    desiredCapacity: 1
    minSize: 2
    maxSize: 4
    volumeSize: 10

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

git:
  repo:
    url: "git@github.com:HenryMhene/devops-development.git"
    branch: master
    fluxPath: "flux/"
    user: "henrymhene"
    email: "thmhene@gmail.com"
  operator:
    namespace: "flux"
    withHelm: true
  bootstrapProfile:
    source: app-dev
    revision: master
